"use client";

import { Newsreader, Inter } from "next/font/google";
import { Videotape } from "lucide-react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { useState } from "react";
import SignInModal from "@/components/sign-in-modal";
import SiteFooter from "@/components/site-footer";

const editorialSerif = Newsreader({
  subsets: ["latin"],
  variable: "--font-editorial",
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700"],
});

const transcriptSans = Inter({
  subsets: ["latin"],
  variable: "--font-transcript-sans",
});

export default function TermsPage() {
  const { data: session } = useSession();
  const [showSignIn, setShowSignIn] = useState(false);

  return (
    <div className={`${editorialSerif.variable} ${transcriptSans.variable} font-serif min-h-screen bg-[#FDFDFD] text-[#111111] antialiased flex flex-col`}>
      <header className="border-b border-gray-100 bg-white/80 backdrop-blur-md px-8 py-5 sticky top-0 z-50">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <Videotape className="h-9 w-9 text-black stroke-[1.5]" />
            <span className="font-sans text-2xl font-bold tracking-tight text-black">
              Tranzkript
            </span>
          </Link>
          <nav className="font-sans text-sm font-medium text-gray-500 flex items-center gap-8">
            <Link href="/features" className="hover:text-black transition-colors">Features</Link>
            <Link href="/pricing" className="hover:text-black transition-colors">Pricing</Link>
            {session?.user ? (
              <Link href="/dashboard" className="font-sans text-sm font-medium text-white bg-black rounded-full px-4 py-1.5 hover:bg-gray-900 transition-colors">Dashboard</Link>
            ) : (
              <button onClick={() => setShowSignIn(true)} className="font-sans text-sm font-medium text-white bg-black rounded-full px-4 py-1.5 hover:bg-gray-900 transition-colors cursor-pointer bg-black border-none">Log In</button>
            )}
          </nav>
        </div>
      </header>

      <main className="mx-auto w-full max-w-3xl flex-1 px-8 py-16">
        <h1 className={`text-4xl md:text-5xl font-bold italic tracking-tight leading-[1.1] text-black mb-6 ${editorialSerif.className} font-editorial`}>
          Terms of Service
        </h1>
        <p className="font-[family-name:var(--font-barlow-condensed)] text-base text-gray-400 mb-8">Last updated: July 27, 2026</p>

        <div className="font-[family-name:var(--font-barlow-condensed)] text-sm text-gray-600 space-y-6 leading-relaxed">
          <section>
            <h2 className="font-bold text-black text-lg mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Tranzkript (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">2. Description of Service</h2>
            <p>
              Tranzkript provides automated transcription of podcast episodes. Users may submit publicly available podcast URLs and receive machine-generated transcripts. Transcripts are provided &quot;as is&quot; and may contain errors.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to circumvent usage limits or access controls</li>
              <li>Submit content that infringes on third-party rights</li>
              <li>Reverse engineer, modify, or create derivative works of the Service</li>
              <li>Use automated tools to scrape or abuse the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">5. Intellectual Property</h2>
            <p>
              The Service, including its design, code, and branding, is owned by Tranzkript and protected by applicable laws. Transcription output generated by the Service is provided for personal use. You are responsible for ensuring your use of transcripts complies with applicable copyright laws.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">6. Limitation of Liability</h2>
            <p>
              Tranzkript is provided on an &quot;as is&quot; and &quot;as available&quot; basis. We make no warranties regarding the accuracy, reliability, or availability of the Service. In no event shall Tranzkript be liable for any damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">7. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time, without notice, for conduct that we believe violates these Terms or is harmful to the Service or other users.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">8. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="font-bold text-black text-lg mb-2">9. Contact</h2>
            <p>
              For questions about these Terms, please contact us at <a href="mailto:support@tranzkript.com" className="underline hover:text-black transition-colors">support@tranzkript.com</a>.
            </p>
          </section>
        </div>
      </main>

      <SiteFooter />
      <SignInModal open={showSignIn} onClose={() => setShowSignIn(false)} />
    </div>
  );
}